version: '3.9'
services:
  todos-restapi:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes:
      - ./todos-restapi:/go/src/github.com/todos-restapi
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
    networks:
      - golang_test_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    networks:
      - golang_test_network

volumes:
  db-data:
    driver: local

networks:
  golang_test_network:
